### PR TITLE
Add keep_backup_amount options

### PR DESCRIPTION
**Pull request by cxssbit**
Add "keep_backup_amount" option for Create backup API endpoint ([https://developers.ploi.io/34-database-backups/100-create-backup](https://developers.ploi.io/34-database-backups/100-create-backup))

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Closed due to inactivity.

**Comment by cvl01** [comment]
@Cannonb4ll Why was this closed? Seems like a valid addition to me. This parameter is part of the API so makes sense to have it here.

**Comment by Cannonb4ll** [comment]
It was closed due to inactivity, and failure to answer my review question which is a fair question. Seems untested and thus unsafe to merge.

Feel free to submit a fresh PR with it properly tested.

**Comment by cvl01** [comment]
Don't see that review question. Also, what would you like tested? The current other parameters like `interval`, `table_exclusions` aren't even tested. 
Looking at the repo only a minor percentage of all the classes are tested. I don't think it is very fair to demand tests for a fully untested class, if the change proposed is only a few lines of adding an extra parameter.

**Comment by Cannonb4ll** [comment]
CleanShot 2024-10-23 at 11 13 01

**Comment by cvl01** [comment]
I think only original pull request author can see that. I agree changing to `?int` is useful. Maybe you can change it yourself and merge, otherwise I'll open a pull.

**Pull request closed without merging**
